### ISSUE TITLE
ValueError: No function '__pyx_fuse_0pdtr' found in __pyx_capi__ of 'scipy.special.cython_special'

### ISSUE THREAD

**Issue by shankardutt** [numba/numba-scipy#40] opened 2020-04-09 10:31 UTC
Hi I am trying to use numba and I am using numba-scipy as a wrapper for scipy special functions. Below is my code:
```
import numpy as np
from scipy import integrate
from scipy.special import erf
from scipy.special import j0
import time
import numba as nb

q = np.linspace(0.03, 1.0, 1000)

start = time.time()

#error_model="numpy" -> Don't check for division by zero
@nb.njit(error_model="numpy",fastmath=True)
def f(t, z, q):
    return t * 0.5 * (erf((t - z) / 3) - 1) * j0(q * t) * (1 / (np.sqrt(2 * np.pi) * 2)) * np.exp(
        -0.5 * ((z - 40) / 2) ** 2)

def lower_inner(z):
    return 10.

def upper_inner(z):
    return 60.


y = np.empty(len(q))
for n in range(len(q)):
    y[n] = integrate.dblquad(f, 0, 50, lower_inner, upper_inner,args=(q[n],))[0]

end = time.time()
print(end - start)
```

I am getting the following error
```
ValueError: No function '__pyx_fuse_0pdtr' found in __pyx_capi__ of 'scipy.special.cython_special'

```

**Comment by stuartarchibald** [comment] 2020-04-09 10:44
Thanks for the report, duplicate of https://github.com/numba/numba-scipy/issues/35.

**Closed** 2020-04-09 10:44 UTC
